import sys
from PyQt6.QtWidgets import QApplication, QMainWindow
from output import Ui_MainWindow  # Assuming output.py was generated by pyuic
 
class MainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)  # This sets up the UI from the converted .py file
        
        # Initialize the count variable to keep track of button clicks
        self.count = 0
 
        # Access the button and connect the click signal
        self.pushButton.clicked.connect(self.on_button_click)
 
    def on_button_click(self):
        print("Button clicked!")
        self.count += 1  # Increment the count with each button click
        print(f"Button clicked {self.count} times")
 
        # Check if the count is even or odd and change button text accordingly
        if self.count % 2 == 0:
            self.pushButton.setText("Clicked")  # Even count: display "Clicked"
        else:
            self.pushButton.setText("Not Clicked")  # Odd count: display "Not Clicked"
 
app = QApplication(sys.argv)
window = MainWindow()
window.show()
sys.exit(app.exec())